'use strict';

function messages() {
    var logs = {};
    logs = {
        "reservCreated": "Reservation has been created.",
        "reservTimeout": "Reservation/ task timeout has happened.",
        "insertCallDetails": "Call details is getting saved into DB",
        "insertCallDetailsFailed": "Saving call details is failed",
        "getElevatorInfo": "Geting elevator information from G3MS is initiated",
        "getAccessTknInitiated": "Getting Azure Access Token to communicate with G3MS is initiated",
        "accessTknErrorUsedDefault": "Getting Azure Access Token failed. Will not be able to couumunicate to G3MS. Default elevator information will be used",
        "gotAccessTknG3MS": "Got Azure Access Token to communicate with G3MS",
        "G3MSCommunicationStarted": "Communication with G3MS is initiated.",
        "gotUnitInfoSuccess": "Got Elevator Unit information successfully",
        "gotUnitInfoFailed": "Getting Elevator Unit information failed. Default elevator information will be used",
        "requestGetUnitInfoTimeout": "Request to G3MS(GetUnitInfoForCCC) timeout.",
        "requestGetDeviceByUnitTimeout": "Request to G3MS(GetDeviceByUnitNumber) timeout.",
        "requestTimeout": "Request to G3MS(GetUnitInfoForCCC) timeout.",
        "gotUnitInfoFailedExp": "Getting Elevator Unit information failed. Status Code is ",
        "gotUnexpectedException": "Got unexpected exception.",
        "elevatorInfoCollStarted": "Gathering Elevator information from response is started.",
        "elevatorInfoCollected": "Elevator information is gathered",
        "decodeOfUnitInfoStarted": "Decoding of elevator information is started",
        "unitInfoDecoded": "Elevator information is decoded. Elevator information is ",
        "elevatorInfoSentBack": "Elevator information is sent back: Final information is ",
        "gotResultBack": "Got elevator infomation",
        "getElevatorInfoFailed": "Getting elevator information is failed",
        "savingElevatorDetailsDB": "Saving elevator/building details to db",
        "savingElevatorDetailsDBSuccess": "Saving elevator/building details back to db is success",
        "savingElevatorDetailsDBFailed": "Saving elevator/building details back to db is failed",
        "acceptTheCallStarted": "Accepting the call is initiated.",
        "acceptTheCallAccepted": "Call is accepted.",
        "connecting2Room": "Connecting to video room",
        "connecting2RoomFailed": "Connecting to room is failed.",
        "videoRoomJoined": "Joining to video room",
        "workerUpdationInitiated": "Updating Worker activity/status is started.",
        "workerUpdationSuccess": "Worker activity/status is updated",
        "workerUpdationFailed": "Worker activity/status updation is failed",
        "leaveRoomIfJoinedInitiated": "Leaving the room if it's joined",
        "leavingRoom": "Leaving room...",
        "completingTaskInitiated": "Completing the current task is initiated.",
        "taskCompleted": "Task is completed",
        "activityUpdated" : "Activity is updated",
        "alreadyInRoom": "Participant track is attached",
        "joiningRoom": "Joining to room",
        "trackAdded": "Track added",
        "callDisconnected": "Room is disconnected",
        "gettingUUIDElevator": "Getting UUID of the elevator.",
        "callGetDeviceByUnitNumber": "Calling G3MS for GetDeviceByUnitNumber API to get UUID of the Elevator. Host: ",
        "gotResponseForGetDeviceByUnitNum": "Got response from G3MS for GetDeviceByUnitNumber API, Status Code is ",
        "startDecodingG3MSResp": "Decoding of G3MS response is initiated",
        "availableDeviceInfo": "Response is decoded and avalilable Elevator Info: ",
        "sendingDeviceCmdtoCIMS": "Sending device command to CIMS, UUID: ",
        "noDeviceFound": "No elevator information found",
        "errWhileRetrievingInfo": "Error while retrieving building information",
        "startElevatorCallBack": "Callback Elevator is initiated",
        "gettingExistingAlarmID": "Getting existing alarmId from local database if it is exist.",
        "startDeviceMsgEncoding": "Encoding of elevator Information is started.",
        "initiateGetAccessTkn": "Getting Azure Access Token is initiated.",
        "gettingAccessTknErr": "Getting Azure Access Token error",
        "gotRespFromCIMS": "Got response from CIMS, status code is ",
        "getAccessTknForCmd": "Getting Azure Access Token for sending command to CIMS",
        "getAccessTknForCmdErr": "Getting Azure Access Token for sending command to CIMS is thrown error, error is ", 
        "gotAccessTknForCmd": "Got Azure Access Token for sending command to CIMS",
        "callingCIMS": "Communication with CIMS is started. Host information is ",
        "gotResponseFromCIMS": "Got response from CIMS. Status Code is ",
        "sendingCMDToCIMSSuccess": "Command sent successfully to CIMS",
        "sendingCMDToCIMSFailed": "Sending command to CIMS failed. Decoded Msg is: ",
        "sendingCMDToCIMSErr": "Sending command to CIMS is returned error. Error is ",
        "startModifyMICGain": "Modifying Mic Gain command is initiated",
        "startElevatorHangup": "Elevator hangup is initiated",
        "sendElevatorHangup": "Sending Elevator Hangup command to CIMS: UUID is",
        "sendModifyMICGain": "Sending Modifying Mic Gain command to CIMS: UUID is",
        "decodeRespFromCIMS": "Decoding the response got from CIMS",
        "decodeRespFromCIMSMsg": "Decoded the response got from CIMS. The message is ",
        "CIMSCmdFailed": "Sending command to CIMS is failed. Error is ",
        "startModifySpeakerVol": "Modifying Speaker volume command is initiated",
        "sendModifySpeakerVol": "Sending Modifying Speaker volume command to CIMS",
        "startAlarmDisp": "Sending alarm disposition to G3MS is initiated",
        "decodeAlarmDispData": "Alarm disposition data are encoded",
        "initiateSendingAlarmDisp": "Sending alarm disposition to G3MS is initiated",
        "callG3MSAPI": "Calling G3MS API",
        "gotRespFromG3MS": "Got response from G3MS. The Status Code is ",
        "writeAlarmDispFailed": "Writing alarm disposition is failed: ",
        "dataTrackAdded": "Data track is added.",
        "vidioTrackAdded": "Video track is added",
        "audioTrackAdded": "Audio track is added",
        "callTransfer": "Request for call transfer is initiated.",
        "callTransferred": "Call transferred successfully",
        "noParticipantTrackAdded": "Call Transferred. But, no participant track is added.",
        "callbackElevatorStarted": "Callback elevator is initiated",
        "callbackElevatorError": "Callback elevator is failed",
        "couldNotConnectTwilio": "Could not connect to Twilio: ",
        "forcedToLogout": "Navigated back during call",
        "tryingCloseDuringCall": "Pressed F5 try to close tab during call",
        "callBackElevatorG3MSSuccess": "Callback elevator: Got elevator info from G3MS",
        "callbackG3MSFailed": "Callback elevator: Failed getting elevator info",
        "workerTokenExpired": "Worker token is expired.",
        "getElevatorDetailsFromDB": "Getting elevator info from DB started",
        "gotElevatorDetailsFromDB": "Got elevator info from DB started",
        "gotElevatorDetailsButUUID": "Got elevator info. But, UUID from DB",
        "saveDispTimeout": "Saving alarm disposition timeout"
    }

    return logs;
}
module.exports = messages();